/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import controller.BillController;
import controller.BookingDetailsController;
import controller.DiscountController;
import controller.RoomController;
import controller.ServiceController;
import controller.ServiceDetailController;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bill;
import model.BookingDetails;
import model.Discount;
import model.LoadRoomNumber;
import model.LoadUserName;
import model.Room;
import model.Service;
import model.ServiceDetail;

/**
 *
 * @author Văn Bảo
 */
public class CheckOutForm extends javax.swing.JFrame {

    /**
     * Creates new form CheckInForm
     */
    float service_chanrge = 0;
    public CheckOutForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        showTable();
        showService();
        showPrice();
    }
    
    
    public void showTable(){
        BookingDetailsController bookingdetails = new BookingDetailsController();
        jTable_check_out.setModel(new DefaultTableModel(null, new Object[]{"Tên khách", "Số điện thoại", "Mail", "Số phòng", "Giá", "Ngày nhận phòng"}));
        DefaultTableModel tableModel = (DefaultTableModel) jTable_check_out.getModel();
        List<BookingDetails> list = bookingdetails.allBookingDetail();

        for (int i = 0; i < list.size(); i++) {

            BookingDetails bd = (BookingDetails)list.get(i);
            Vector row = new Vector();
            row.add(bd.getFullname_client());
            row.add(bd.getPhone_number());
            row.add(bd.getMail());
            row.add(bd.getRoom_number());
            row.add(bd.getPrice());
            row.add(bd.getDate_in());
            tableModel.addRow(row);
        }
    }

    
    
    
    
    public void showService(){
        ServiceController service = new ServiceController();
        List<Service> listType = service.allService();
        jComboBox_service.removeAllItems();
        for(Service item: listType)
        {
           jComboBox_service.addItem(item.getService_name());
        }
    } 
    
    public void showPrice(){
        String service_name = (String) jComboBox_service.getSelectedItem();
        int amount = (Integer) jSpinner_amount.getValue();
        ServiceController service = new ServiceController();
        List<Service> listType = service.loadPrice(service_name);
        for(Service item: listType)
        {
            jLabel_price_unit.setText(String.valueOf(item.getPrice_unit()*amount));
        }
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_search = new javax.swing.JTextField();
        jButton_search = new javax.swing.JButton();
        jButton_check_out = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_check_out = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField_discount_code = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_name_client = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel_phone = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel_room_number = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel_date_in = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox_service = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel_price_unit = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSpinner_amount = new javax.swing.JSpinner();
        jButton_add_service = new javax.swing.JButton();
        jButton_service_detail = new javax.swing.JButton();
        jButton_apply = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1297, 782));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 40));

        jLabel_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Check out");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Close)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_Close))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 204, 51));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gg-circle.png"))); // NOI18N
        jLabel13.setText("Hotel");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextField_search.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_search.setToolTipText("Nhập số phòng...");

        jButton_search.setBackground(new java.awt.Color(255, 255, 255));
        jButton_search.setForeground(new java.awt.Color(0, 0, 0));
        jButton_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jButton_search.setText("Tìm");
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });

        jButton_check_out.setBackground(new java.awt.Color(255, 153, 51));
        jButton_check_out.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_check_out.setForeground(new java.awt.Color(255, 255, 255));
        jButton_check_out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check-out24px.png"))); // NOI18N
        jButton_check_out.setText("Trả phòng");
        jButton_check_out.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_check_out.setPreferredSize(new java.awt.Dimension(106, 23));
        jButton_check_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_check_outMouseClicked(evt);
            }
        });

        jTable_check_out.setAutoCreateRowSorter(true);
        jTable_check_out.setBackground(new java.awt.Color(255, 255, 255));
        jTable_check_out.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable_check_out.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên khách", "Số điện thoại", "Mail", "Số phòng", "Giá", "Ngày nhận phòng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_check_out.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_check_out.setRowHeight(40);
        jTable_check_out.setSelectionBackground(new java.awt.Color(0, 102, 255));
        jTable_check_out.setVerifyInputWhenFocusTarget(false);
        jTable_check_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_check_outMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_check_out);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nhập số phòng:");

        jTextField_discount_code.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_discount_code.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_discount_code.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_discount_code.setToolTipText("Mã giảm giá");
        jTextField_discount_code.setActionCommand("<Not Set>");
        jTextField_discount_code.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Mã giảm giá:");

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tên khách:");

        jLabel_name_client.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_name_client.setForeground(new java.awt.Color(0, 0, 0));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("SĐT:");

        jLabel_phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_phone.setForeground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Số phòng:");

        jLabel_room_number.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_room_number.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Ngày vào:");

        jLabel_date_in.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_date_in.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_name_client, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel_room_number, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel_date_in, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel_name_client, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel_room_number, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel_date_in, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Dịch vụ:");

        jComboBox_service.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_service.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_service.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_service.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_serviceMouseClicked(evt);
            }
        });
        jComboBox_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_serviceActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Giá:");

        jLabel_price_unit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_price_unit.setForeground(new java.awt.Color(0, 0, 0));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Số lượng:");

        jSpinner_amount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinner_amount.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        jSpinner_amount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinner_amount.setMinimumSize(new java.awt.Dimension(64, 30));
        jSpinner_amount.setPreferredSize(new java.awt.Dimension(50, 23));
        jSpinner_amount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_amountStateChanged(evt);
            }
        });

        jButton_add_service.setBackground(new java.awt.Color(0, 153, 0));
        jButton_add_service.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_add_service.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add_service.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-new.png"))); // NOI18N
        jButton_add_service.setText("Thêm");
        jButton_add_service.setPreferredSize(new java.awt.Dimension(106, 23));
        jButton_add_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_serviceActionPerformed(evt);
            }
        });

        jButton_service_detail.setBackground(new java.awt.Color(153, 153, 0));
        jButton_service_detail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_service_detail.setForeground(new java.awt.Color(255, 255, 255));
        jButton_service_detail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eye.png"))); // NOI18N
        jButton_service_detail.setText("Chi tiết");
        jButton_service_detail.setPreferredSize(new java.awt.Dimension(106, 23));
        jButton_service_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_service_detailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(38, 38, 38)
                .addComponent(jComboBox_service, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel_price_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel16)
                .addGap(33, 33, 33)
                .addComponent(jSpinner_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jButton_add_service, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton_service_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox_service, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(jLabel15))
                    .addComponent(jLabel_price_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_service_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_add_service, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinner_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel16)))
                .addGap(40, 40, 40))
        );

        jButton_apply.setBackground(new java.awt.Color(51, 102, 255));
        jButton_apply.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_apply.setForeground(new java.awt.Color(255, 255, 255));
        jButton_apply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coupon.png"))); // NOI18N
        jButton_apply.setText("Áp dụng");
        jButton_apply.setPreferredSize(new java.awt.Dimension(106, 23));
        jButton_apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_applyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1)
                        .addGap(532, 532, 532)
                        .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_search))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField_discount_code, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(39, 39, 39)
                                    .addComponent(jButton_apply, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(jButton_check_out, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel13))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton_search)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_discount_code, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_check_out, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_apply, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1297, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        
        
        if(jTextField_search.getText().equals("")){
            showTable();
        }else{
            
            int room_number = Integer.parseInt(jTextField_search.getText());
            BookingDetailsController bookingdetails = new BookingDetailsController();
            jTable_check_out.setModel(new DefaultTableModel(null, new Object[]{"Tên khách", "Số điện thoại", "Mail", "Số phòng", "Giá", "Ngày nhận phòng"}));
            DefaultTableModel tableModel = (DefaultTableModel) jTable_check_out.getModel();
            List<BookingDetails> list = bookingdetails.search(room_number);

            if(list.size() == 0){
                JOptionPane.showMessageDialog(rootPane, "Không tìm thấy!", "Thoát", JOptionPane.OK_OPTION);
            }else{
                for (int i = 0; i < list.size(); i++) {

                BookingDetails bd = (BookingDetails)list.get(i);
                    Vector row = new Vector();
                    row.add(bd.getFullname_client());
                    row.add(bd.getPhone_number());
                    row.add(bd.getMail());
                    row.add(bd.getRoom_number());
                    row.add(bd.getPrice());
                    row.add(bd.getDate_in());                   
                    tableModel.addRow(row);
                }
                jTextField_search.setText("");
            } 
        }

    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jButton_check_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_check_outMouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn trả phòng?", "Chọn", JOptionPane.YES_NO_OPTION);
        if(a==0){
            DefaultTableModel model = (DefaultTableModel)jTable_check_out.getModel();
            int rowIndex = jTable_check_out.getSelectedRow();
            int room_number = Integer.parseInt(model.getValueAt(rowIndex,3).toString());

            String fullname_client = model.getValueAt(rowIndex,0).toString();
            String phone_client = model.getValueAt(rowIndex,1).toString(); 
            String mail = model.getValueAt(rowIndex,2).toString();

            Float price_unit = Float.parseFloat(model.getValueAt(rowIndex,4).toString());
            String datein = model.getValueAt(rowIndex,5).toString();

            LoadUserName user = new LoadUserName();
            String add_by = user.getUser_name();

            //Tính số ngày 
            DateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date currentDate = new Date();
            String dateout = simpleDateFormat.format(currentDate);
            long numberday = 0;
            try {

                Date date_start = simpleDateFormat.parse(datein);
                Date date_end = simpleDateFormat.parse(dateout);

                long getDiff = date_end.getTime() - date_start.getTime();
                numberday = getDiff / (24 * 60 * 60 * 1000);

            }catch (Exception e) {
                e.printStackTrace();
            } 



            //Tính tông tiền
            float discount_price = 0;
            String discount_code = jTextField_discount_code.getText().toString();
            String date_now = simpleDateFormat.format(currentDate);
            DiscountController  discountC = new DiscountController();
            List<Discount> list = discountC.checkDiscount(discount_code, date_now);
            if(list.size()<1){
                discount_price = 100;
            }
            else{
                for(Discount item:list){
                    discount_price = item.getDiscount_price();
                }
            }
            
            float price_total;
            if(numberday == 0){
                price_total = price_unit;
            }else{
                price_total = price_unit * numberday;
            }
            ServiceDetailController detailC = new ServiceDetailController();
            List<ServiceDetail> listType = detailC.allServiceBill(room_number);

            for(ServiceDetail item: listType)
            {
                service_chanrge +=item.getPrice_total();
            }

            price_total = (price_total + service_chanrge)*discount_price/100;
            
            
            



            if(discount_price == 100){
                discount_price = 0;
            }
            Date date_in;
            Date date_out;   
            
            //Thêm hóa đơn
            try {
                date_in = new SimpleDateFormat("yyyy-MM-dd").parse(datein);
                date_out = new SimpleDateFormat("yyyy-MM-dd").parse(dateout);
                Bill bill = new Bill(fullname_client, phone_client, mail, room_number, date_in, date_out, price_unit, service_chanrge, discount_price, price_total, add_by);
                bill.setFullname_client(fullname_client);
                bill.setPhone_client(phone_client);
                bill.setMail(mail);
                bill.setRoom_number(room_number);
                bill.setPrice_unit(price_unit);
                bill.setDate_in(date_in);
                bill.setDate_out(date_out);
                bill.setService_charge(service_chanrge);
                bill.setDiscount_price(discount_price);
                bill.setPrice_total(price_total);
                bill.setAdd_by(add_by);

                BillController.add(bill);
                //in hóa đơn
                PrintBill();
                // Xóa khỏi bookingdetail
                BookingDetailsController.delete(room_number);
                showTable(); 
                //Xóa khỏi servicedetail
                ServiceDetailController.delete(room_number);
                //update status
                String status = "Empty";
                Room room = new Room(room_number, status);
                room.setStatus(status);
                room.setRoom_number(room_number);
                RoomController.updateStatus(room);


            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Trả phòng thất bại!", "Lỗi", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_check_outMouseClicked
    
    
    
    public void PrintBill(){
        int bill_code=0;
        String fullname_client = "";
        String phone = "";
        String mail = "";
        float price_unit = 0;
        Date date_in = null;
        Date date_out = null;
        float price_total = 0;
        try {
            
            
            //Lấy thông tin bill
            DefaultTableModel model = (DefaultTableModel)jTable_check_out.getModel();
            int rowIndex = jTable_check_out.getSelectedRow();
            int room_number = Integer.parseInt(model.getValueAt(rowIndex,3).toString());
            BillController billC = new BillController();
            List<Bill> list = billC.findRoomNumber(room_number);
            
            for (int i = 0; i < list.size(); i++) {
                Bill bd = (Bill)list.get(i);
                bill_code = bd.getId_bill();
                fullname_client = bd.getFullname_client();
                phone = bd.getPhone_client();
                mail = bd.getMail();
                price_unit = bd.getPrice_unit();
                date_in = bd.getDate_in();
                date_out = bd.getDate_out();
                price_total = bd.getPrice_total();
            }

            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(new File("d://HoaDon.pdf")));
            //open
            document.open();
            
            Font font = new Font();
            font.setStyle(Font.BOLD);
            font.setSize(28);
            document.add(new Paragraph("GG HOTEL", font));
            document.add(new Paragraph("                         BILL                    \n\n", font));
            
            
            Font f1 = new Font();
            f1.setSize(18);
            document.add(new Paragraph("**************************************************************************\n",f1));
            document.add(new Paragraph("                    Code bill:                      HD "+bill_code, f1));
            document.add(new Paragraph("                    Fullname client:            "+fullname_client, f1));
            document.add(new Paragraph("                    Phone number:             "+phone, f1));
            document.add(new Paragraph("                    Gmail:                           "+mail, f1));
            document.add(new Paragraph("                    Room number:              "+room_number, f1));
            document.add(new Paragraph("                    Unit price:                      "+price_unit+" vnd", f1));
            document.add(new Paragraph("                    Service chanrge:          "+service_chanrge+" vnd", f1));
            document.add(new Paragraph("                    Date check in:               "+date_in, f1));
            document.add(new Paragraph("                    Date check out:             "+date_out, f1));
            document.add(new Paragraph("                    Total price:                    "+price_total+" vnd", f1));
            document.add(new Paragraph("\n*************************************************************************",f1));

            Font f = new Font();
            f.setStyle(Font.ITALIC);
            f.setSize(18);
            document.add(new Paragraph("\nThanh you for using the GG hotel, please visit again...", f));

            //close
            document.close();

            
         
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn in hóa đơn?", "Chọn", JOptionPane.YES_NO_OPTION);
        if(a==0){
            try {
                File file = new File("D:\\HOADON.pdf");
                if(file.exists()){
                    //Process p = Runtime.getRuntime().exec("D:\\HOADON.pdf");
                    if(Desktop.isDesktopSupported()){
                        Desktop.getDesktop().open(file);
                    }
                }
                else{
                    System.out.println("Không thể đóng file!");
                }
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
        }
    }
    
    
    private void jTable_check_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_check_outMouseClicked

        DefaultTableModel model = (DefaultTableModel)jTable_check_out.getModel();
        int rowIndex = jTable_check_out.getSelectedRow();
        //int room_number = Integer.parseInt(model.getValueAt(rowIndex,3).toString());
        this.jLabel_name_client.setText(model.getValueAt(rowIndex,0).toString());
        this.jLabel_phone.setText(model.getValueAt(rowIndex,1).toString());
        this.jLabel_room_number.setText(model.getValueAt(rowIndex,3).toString());
        this.jLabel_date_in.setText(model.getValueAt(rowIndex,5).toString());
    }//GEN-LAST:event_jTable_check_outMouseClicked

    private void jComboBox_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_serviceActionPerformed
        showPrice();
    }//GEN-LAST:event_jComboBox_serviceActionPerformed

    private void jComboBox_serviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_serviceMouseClicked
        // TODO add your handling code here:
        showPrice();
    }//GEN-LAST:event_jComboBox_serviceMouseClicked

    private void jSpinner_amountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_amountStateChanged
        showPrice();
    }//GEN-LAST:event_jSpinner_amountStateChanged

    private void jButton_add_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_serviceActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn sử dụng dịch vụ đã chọn?", "Chọn", JOptionPane.YES_NO_OPTION);
        if(a==0){
            if(jLabel_name_client.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Chọn khách hàng sử dụng dịch vụ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            else{
                int room_number = Integer.parseInt(jLabel_room_number.getText());
                String service_name = (String) jComboBox_service.getSelectedItem();
                float price_unit = 0; 
                ServiceController service = new ServiceController();
                List<Service> listType = service.loadPrice(service_name);
                for(Service item: listType)
                {
                    price_unit = item.getPrice_unit();
                }
                int amount = (Integer) jSpinner_amount.getValue();
                float price_total = price_unit*amount;
                Date date_buy = new Date();
                ServiceDetail detail = new ServiceDetail();
                detail.setRoom_number(room_number);
                detail.setService_name(service_name);
                detail.setPrice_unit(price_unit);
                detail.setAmount(amount);
                detail.setPrice_total(price_total);
                detail.setDate_buy(date_buy);
                try 
                {
                    ServiceDetailController.add(detail);
                    JOptionPane.showMessageDialog(rootPane, "Thêm dịch thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Thêm thất bại!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
        
    }//GEN-LAST:event_jButton_add_serviceActionPerformed

    private void jButton_service_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_service_detailActionPerformed
        // TODO add your handling code here:
        
        if(jLabel_name_client.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Chọn khách hàng sử dụng dịch vụ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int room_number = Integer.parseInt(jLabel_room_number.getText());
            LoadRoomNumber l = new LoadRoomNumber();
            l.setRoom_number(room_number);
            new ServiceDetailForm().setVisible(true);
        }
        
    }//GEN-LAST:event_jButton_service_detailActionPerformed

    private void jButton_applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_applyActionPerformed
        // TODO add your handling code here:
        String discount_code = jTextField_discount_code.getText().toString();
        DateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date currentDate = new Date();
        String date_now = simpleDateFormat.format(currentDate);
        DiscountController  discountC = new DiscountController();
        List<Discount> list = discountC.checkDiscount(discount_code, date_now);
        if(list.size()<1){
            JOptionPane.showMessageDialog(rootPane, "Mã giảm giá đã hết hạng hoặc không tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Áp dụng thành công!", "Thoát", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton_applyActionPerformed

    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add_service;
    private javax.swing.JButton jButton_apply;
    private javax.swing.JButton jButton_check_out;
    private javax.swing.JButton jButton_search;
    private javax.swing.JButton jButton_service_detail;
    private javax.swing.JComboBox<String> jComboBox_service;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_date_in;
    private javax.swing.JLabel jLabel_name_client;
    private javax.swing.JLabel jLabel_phone;
    private javax.swing.JLabel jLabel_price_unit;
    private javax.swing.JLabel jLabel_room_number;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_amount;
    private javax.swing.JTable jTable_check_out;
    private javax.swing.JTextField jTextField_discount_code;
    private javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables
}
